version: "3.9"

networks:
  default:
    name: github-dev
    external: true

services:
  api:
    image: flask-docker:latest
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: flask --app src.flask_docker.app:app run --host 0.0.0.0 --port 8000 --debug
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/status"]
      interval: 60s
      timeout: 5s
      retries: 3
